export const categoriesDB = {
    'ROL' : 'ROLLS',
    'RIC' : 'RICE',
    'BUR' : 'BURGERS',
    'PAR' : 'PARATHAS',
    'NOD' : 'NOODLES',
    'MAG' : 'MAGGIE',
    'SAN' : 'SABDWICHES',
    'FRI' : 'FRIES',
    'PAK' : 'PAKODAS',
    'COF' : 'COFFEE',
    'TEA' : 'TEA',
    'BEV' : 'BEVERAGES',
    'BRE' : 'BREAKFAST',
    'OME' : 'OMELETTE',
    'MEA' : 'MEALS',
    'PAS' : 'PASTAS',
    'LAS' : 'LASSI',
    'SOD' : 'SODA',
    'SHA' : 'SHAKES',
    'MIL' : 'MILK',
    'JUC' : 'JUICES',
    'MOM' : 'MOMOS',
    'CHA' : 'CHATS'
};